# This is a basic workflow to help you get started with Actions

name: CI

on:
  create: { }
  push: { }
  pull_request: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Prepare and run build
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io
          sudo systemctl unmask docker.service
          sudo systemctl start docker.socket || sudo systemctl status docker.socket
          sudo systemctl start docker.service || sudo systemctl status docker.service
          sudo journalctl -xe
          sudo docker rm archlinux || true
          sudo docker run --name archlinux -v "$(realpath "$GITHUB_WORKSPACE")":/linux2boot archlinux:latest /linux2boot/build.sh

      # Upload artifacts
      # First party upload plugin is magic and does not need github token
      - name: Upload shasums
        uses:  actions/upload-artifact@v2-preview
        with:
          name: shasums
          path: SHA256SUMS

      - name: Upload release info
        uses:  actions/upload-artifact@v1
        with:
          name: release-info
          path: release_info.txt

      - name: Upload package
        uses:  actions/upload-artifact@v2-preview
        with:
          name: package
          path: "*.pkg.tar.xz"


  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Download shasums
        uses:  actions/download-artifact@v1
        with:
          name: shasums

      - name: Download release info
        uses:  actions/download-artifact@v1
        with:
          name: release-info

      - name: Dwonload package
        uses:  actions/download-artifact@v1
        with:
          name: package

      # Upload actual release
      # build job is likely to take more than an hour, secrets.GITHUB_TOKEN would have expired
      - name: Release build artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: release_info.txt
          files: |
            "*.pkg.tar.xz"
            SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
