# This is a basic workflow to help you get started with Actions

name: CI

on:
  create: { }
  push: { }
  pull_request: { }

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      pkgfile: ${{ steps.pkgname.outputs.pkgfile }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Prepare and run build
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io
          sudo systemctl unmask docker.service
          sudo systemctl start docker.socket || sudo systemctl status docker.socket
          sudo systemctl start docker.service || sudo systemctl status docker.service
          sudo journalctl -xe
          sudo docker rm archlinux || true
          sudo docker run --name archlinux -v "$(realpath "$GITHUB_WORKSPACE")":/linux2boot archlinux:latest /linux2boot/build.sh

      # Upload artifacts
      # First party upload plugin is magic and does not need github token
      - name: Upload shasums
        uses: actions/upload-artifact@v2-preview
        with:
          name: SHA256SUMS
          path: SHA256SUMS

      - name: Upload release info
        uses: actions/upload-artifact@v1
        with:
          name: release_info.txt
          path: release_info.txt

      - id: pkgname
        name: Find package name
        run: echo "::set-output name=pkgfile::$(ls *.pkg.tar.xz)"

      - name: Upload package
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ steps.pkgname.outputs.pkgfile }}
          path: ${{ steps.pkgname.outputs.pkgfile }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Download shasums
        uses: actions/download-artifact@v1
        with:
          name: SHA256SUMS

      - name: Download release info
        uses: actions/download-artifact@v1
        with:
          name: release_info.txt

      - name: Download package
        uses: actions/download-artifact@v1
        with:
          name: ${{ needs.build.outputs.pkgfile }}

      - name: Copious amount of debug ls
        run: |
          ls -la .
          ls -la linux2boot-pbp || true
          ls -la release_info.txt || true
          ls -la linux2boot-pbp/release_info.txt || true
          ls -la linux2boot-pinebookpro-0.7-1-any.pkg.tar.xz || true
          ls -la linux2boot-pbp/linux2boot-pinebookpro-0.7-1-any.pkg.tar.xz || true

      # Upload actual release
      # build job is likely to take more than an hour, secrets.GITHUB_TOKEN would have expired
      - name: Release build artifacts
        uses: softprops/action-gh-release@v1
        with:
          body_path: release_info.txt
          files: |
            "*.pkg.tar.xz"
            SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
